import type { Metadata } from 'next';
import './globals.css';
import { poppins } from '@/fonts';
import { cn } from '@/utils';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const RootLayout = ({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) => {
	return (
		<html lang='en'>
			<body className={cn(poppins.className)}>{children}</body>
		</html>
	);
};

export default RootLayout;
