import type { Metadata } from 'next';
import './globals.css';
import { poppins } from '@/fonts';
import { cn } from '@/utils';
import { Nav } from '@/components/nav';
import { Footer } from '@/components/footer';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const RootLayout = ({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) => {
	return (
		<html lang='en'>
			<body className={cn(poppins.className)}>
				<Nav></Nav>
				{children}
				<Footer></Footer>
			</body>
		</html>
	);
};

export default RootLayout;
